import torch
try:
    import triton
    import triton.language as tl
except ImportError:
    triton = None
    tl = None

if triton is not None:
    @triton.jit
    def kernel_0_cpu(
        Image_ptr
    ):
        # Lowered operation: Image (Input)
        pass

if triton is not None:
    @triton.jit
    def kernel_1_cpu(
        Filter_ptr
    ):
        # Lowered operation: Filter (Input)
        pass

if triton is not None:
    @triton.jit
    def kernel_2_cpu(
        Classifier_ptr
    ):
        # Lowered operation: Classifier (Input)
        pass

if triton is not None:
    @triton.jit
    def kernel_3_gpu(
    ):
        # Lowered operation: Conv (Conv2D)
        pass

if triton is not None:
    @triton.jit
    def kernel_4_gpu(
    ):
        # Lowered operation: Pool (MaxPool)
        pass

if triton is not None:
    @triton.jit
    def kernel_5_cpu(
    ):
        # Lowered operation: Flat (Reshape)
        pass

if triton is not None:
    @triton.jit
    def kernel_6_gpu(
    ):
        # Lowered operation: Logits (MatMul)
        pass

if triton is not None:
    @triton.jit
    def kernel_7_cpu(
    ):
        # Lowered operation: O (Output)
        pass


# Graph-correct PyTorch fallback generated by Thiran
def run_compiled_graph(inputs=None):
    inputs = {} if inputs is None else inputs
    runtime_device = 'cuda' if torch.cuda.is_available() else 'cpu'
    outputs = {}

    # kernel_0_cpu (CPU)
    v_Image = inputs.get('Image')
    if v_Image is None:
        v_Image = torch.randn((1, 1, 8, 8), device=runtime_device)

    # kernel_1_cpu (CPU)
    v_Filter = inputs.get('Filter')
    if v_Filter is None:
        v_Filter = torch.randn((2, 1, 3, 3), device=runtime_device)

    # kernel_2_cpu (CPU)
    v_Classifier = inputs.get('Classifier')
    if v_Classifier is None:
        v_Classifier = torch.randn((18, 4), device=runtime_device)

    # kernel_3_gpu (GPU)
    v_Conv = torch.nn.functional.conv2d(v_Image, v_Filter)

    # kernel_4_gpu (GPU)
    v_Pool = torch.nn.functional.max_pool2d(v_Conv, kernel_size=2)

    # kernel_5_cpu (CPU)
    v_Flat = torch.reshape(v_Pool, (1, 18))

    # kernel_6_gpu (GPU)
    v_Logits = torch.matmul(v_Flat, v_Classifier)

    # kernel_7_cpu (CPU)
    outputs['O'] = v_Logits

    return outputs

if __name__ == '__main__':
    for name, value in run_compiled_graph().items():
        print(f'{name}: {tuple(value.shape)}')
