#include "backend/PythonExecutorEmitter.hpp"

#include <cctype>
#include <sstream>
#include <unordered_set>

namespace thiran
{

namespace
{

std::string valueName(Node* node)
{
    std::string name = "v_";
    for(char character : node->name)
    {
        name += std::isalnum(static_cast<unsigned char>(character)) ? character : '_';
    }
    return name;
}

std::string shapeLiteral(const std::vector<int>& shape)
{
    std::stringstream out;
    out << "(";
    for(size_t i = 0; i < shape.size(); ++i)
    {
        if(i) out << ", ";
        out << shape[i];
    }
    if(shape.size() == 1) out << ",";
    out << ")";
    return out.str();
}

std::string input(Node* node, size_t index)
{
    return index < node->inputs.size() ? valueName(node->inputs[index]) : "None";
}

}

std::string PythonExecutorEmitter::emit(BackendIR& backend)
{
    std::stringstream out;
    std::unordered_set<Node*> emitted;

    out << "\n# Graph-correct PyTorch fallback generated by Thiran\n";
    out << "def run_compiled_graph(inputs=None):\n";
    out << "    inputs = {} if inputs is None else inputs\n";
    out << "    runtime_device = 'cuda' if torch.cuda.is_available() else 'cpu'\n";
    out << "    outputs = {}\n\n";

    for(auto& kernel : backend.kernels)
    {
        out << "    # " << kernel->name << " (" << toString(kernel->device) << ")\n";

        for(auto node : kernel->operations)
        {
            if(!emitted.insert(node).second) continue;

            const std::string self = valueName(node);
            const std::string a = input(node, 0);
            const std::string b = input(node, 1);

            switch(node->op)
            {
                case Operation::Input:
                    out << "    " << self << " = inputs.get('" << node->name << "')\n";
                    out << "    if " << self << " is None:\n";
                    out << "        " << self << " = torch.randn(" << shapeLiteral(node->shape)
                        << ", device=runtime_device)\n";
                    break;
                case Operation::Constant:
                    if(node->shape.empty())
                        out << "    " << self << " = torch.tensor(" << node->constantValue
                            << ", dtype=torch.float32, device=runtime_device)\n";
                    else
                        out << "    " << self << " = torch.full(" << shapeLiteral(node->shape) << ", "
                            << node->constantValue << ", dtype=torch.float32, device=runtime_device)\n";
                    break;
                case Operation::Add: out << "    " << self << " = " << a << " + " << b << "\n"; break;
                case Operation::Subtract: out << "    " << self << " = " << a << " - " << b << "\n"; break;
                case Operation::Multiply: out << "    " << self << " = " << a << " * " << b << "\n"; break;
                case Operation::Divide: out << "    " << self << " = " << a << " / " << b << "\n"; break;
                case Operation::MatMul: out << "    " << self << " = torch.matmul(" << a << ", " << b << ")\n"; break;
                case Operation::FusedMatMulRelu:
                    out << "    " << self << " = torch.relu(torch.matmul(" << a << ", " << b << "))\n";
                    break;
                case Operation::Conv2D:
                    out << "    " << self << " = torch.nn.functional.conv2d(" << a << ", " << b << ")\n";
                    break;
                case Operation::ReLU: out << "    " << self << " = torch.relu(" << a << ")\n"; break;
                case Operation::Sigmoid: out << "    " << self << " = torch.sigmoid(" << a << ")\n"; break;
                case Operation::Tanh: out << "    " << self << " = torch.tanh(" << a << ")\n"; break;
                case Operation::Softmax: out << "    " << self << " = torch.softmax(" << a << ", dim=-1)\n"; break;
                case Operation::MaxPool:
                    out << "    " << self << " = torch.nn.functional.max_pool2d(" << a << ", kernel_size=2)\n";
                    break;
                case Operation::AvgPool:
                    out << "    " << self << " = torch.nn.functional.avg_pool2d(" << a << ", kernel_size=2)\n";
                    break;
                case Operation::Reshape: out << "    " << self << " = torch.reshape(" << a << ", " << shapeLiteral(node->shape) << ")\n"; break;
                case Operation::Transpose: out << "    " << self << " = torch.transpose(" << a << ", 0, 1)\n"; break;
                case Operation::Transfer:
                    out << "    " << self << " = " << a << ".to(runtime_device)\n";
                    break;
                case Operation::Output:
                    out << "    outputs['" << node->name << "'] = " << a << "\n";
                    break;
                default:
                    out << "    # Unsupported operation " << toString(node->op) << "\n";
                    break;
            }
        }
        out << "\n";
    }

    out << "    return outputs\n\n";
    out << "if __name__ == '__main__':\n";
    out << "    for name, value in run_compiled_graph().items():\n";
    out << "        print(f'{name}: {tuple(value.shape)}')\n";

    return out.str();
}

}
