if(NOT DEFINED THIRAN_EXECUTABLE OR
   NOT DEFINED SOURCE_DIR OR
   NOT DEFINED TEST_BINARY_DIR OR
   NOT DEFINED PYTHON_EXECUTABLE)
    message(FATAL_ERROR "RegionExecutionTests requires executable, source, binary, and Python paths")
endif()

set(usage
"Usage:
  Thiran <source-file>
  Thiran --plan <source-file>
  Thiran --emit-plan <source-file> <output-file>
  Thiran --emit-region-executor <source-file> <output-file>
  Thiran --version
  Thiran --help
")

file(REMOVE_RECURSE "${TEST_BINARY_DIR}")
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}")
set(cnn "${SOURCE_DIR}/examples/cnn.th")
set(mlp "${SOURCE_DIR}/examples/mlp.th")
set(fixture "${SOURCE_DIR}/tests/fixtures/region_execution_multi_output_constant.th")

function(run_thiran result_var stdout_var stderr_var)
    execute_process(
        COMMAND "${THIRAN_EXECUTABLE}" ${ARGN}
        WORKING_DIRECTORY "${TEST_BINARY_DIR}"
        RESULT_VARIABLE result
        OUTPUT_VARIABLE stdout
        ERROR_VARIABLE stderr
    )
    set(${result_var} "${result}" PARENT_SCOPE)
    set(${stdout_var} "${stdout}" PARENT_SCOPE)
    set(${stderr_var} "${stderr}" PARENT_SCOPE)
endfunction()

function(require_equal actual expected label)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "${label}: values differ\nexpected=[${expected}]\nactual=[${actual}]")
    endif()
endfunction()

function(require_contains text token label)
    string(FIND "${text}" "${token}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "${label}: missing [${token}]")
    endif()
endfunction()

function(require_executor path label)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "${label}: artifact absent")
    endif()
    file(READ "${path}" source)
    if(NOT source MATCHES "^# Generated by Thiran RegionPythonEmitter")
        message(FATAL_ERROR "${label}: invalid header")
    endif()
    foreach(token "run_region_plan" "_region_" "strategy:")
        require_contains("${source}" "${token}" "${label}")
    endforeach()
    foreach(token "0x" "torch.randn" "import triton")
        string(FIND "${source}" "${token}" position)
        if(NOT position EQUAL -1)
            message(FATAL_ERROR "${label}: forbidden token [${token}]")
        endif()
    endforeach()
endfunction()

function(emit_executor source output label)
    run_thiran(result stdout stderr
        --emit-region-executor "${source}" "${output}")
    require_equal("${result}" "0" "${label} exit")
    require_equal(
        "${stdout}"
        "Wrote Region-controlled Python executor: ${output}\n"
        "${label} stdout")
    require_equal("${stderr}" "" "${label} stderr")
    require_executor("${output}" "${label}")
endfunction()

# Case 1: updated help.
foreach(option --help -h)
    run_thiran(result stdout stderr "${option}")
    require_equal("${result}" "0" "help exit")
    require_equal("${stdout}" "${usage}" "help stdout")
    require_equal("${stderr}" "" "help stderr")
endforeach()

# Case 2: invalid usage.
foreach(arguments
    "--emit-region-executor"
    "--emit-region-executor;source.th"
    "--emit-region-executor;source.th;out.py;extra")
    file(REMOVE "${TEST_BINARY_DIR}/out.py")
    run_thiran(result stdout stderr ${arguments})
    require_equal("${result}" "2" "invalid executor usage exit")
    require_equal("${stdout}" "" "invalid executor usage stdout")
    require_contains("${stderr}" "${usage}" "invalid executor usage")
    if(EXISTS "${TEST_BINARY_DIR}/out.py")
        message(FATAL_ERROR "invalid usage created artifact")
    endif()
endforeach()

# Cases 3 and 4: CNN and MLP emission.
set(cnn_executor "${TEST_BINARY_DIR}/cnn-region.py")
set(mlp_executor "${TEST_BINARY_DIR}/mlp-region.py")
emit_executor("${cnn}" "${cnn_executor}" "CNN executor")
emit_executor("${mlp}" "${mlp_executor}" "MLP executor")

# Case 5: deterministic artifact.
set(cnn_executor_second "${TEST_BINARY_DIR}/cnn-region-second.py")
emit_executor("${cnn}" "${cnn_executor_second}" "second CNN executor")
file(SHA256 "${cnn_executor}" first_hash)
file(SHA256 "${cnn_executor_second}" second_hash)
require_equal("${first_hash}" "${second_hash}" "deterministic artifact")

# Case 6: repository artifact isolation.
foreach(artifact generated.py graph.dot region_plan.txt)
    if(EXISTS "${SOURCE_DIR}/${artifact}")
        set("${artifact}_existed" TRUE)
        file(READ "${SOURCE_DIR}/${artifact}" "${artifact}_before")
    else()
        set("${artifact}_existed" FALSE)
    endif()
endforeach()
emit_executor("${cnn}" "${cnn_executor}" "isolated CNN executor")
emit_executor("${mlp}" "${mlp_executor}" "isolated MLP executor")
foreach(artifact generated.py graph.dot region_plan.txt)
    if(${artifact}_existed)
        file(READ "${SOURCE_DIR}/${artifact}" artifact_after)
        require_equal("${artifact_after}" "${${artifact}_before}" "${artifact} isolation")
    elseif(EXISTS "${SOURCE_DIR}/${artifact}")
        message(FATAL_ERROR "${artifact} was created in repository root")
    endif()
endforeach()

function(compare_program label source executor python_body)
    run_thiran(normal_result normal_stdout normal_stderr "${source}")
    require_equal("${normal_result}" "0" "${label} normal compile")
    emit_executor("${source}" "${executor}" "${label} executor")
    set(script "${TEST_BINARY_DIR}/${label}-compare.py")
    file(WRITE "${script}"
"import importlib.util
import torch
def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module
whole = load('whole_${label}', r'${TEST_BINARY_DIR}/generated.py')
region = load('region_${label}', r'${executor}')
${python_body}
reference = whole.run_compiled_graph(inputs)
actual = region.run_region_plan(inputs)
assert list(reference.keys()) == list(actual.keys())
for key in reference:
    assert reference[key].shape == actual[key].shape
    assert reference[key].dtype == actual[key].dtype
    torch.testing.assert_close(actual[key], reference[key], rtol=1e-5, atol=1e-6)
")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env
            "CUDA_VISIBLE_DEVICES="
            "PYTHONDONTWRITEBYTECODE=1"
            "${PYTHON_EXECUTABLE}" "${script}"
        WORKING_DIRECTORY "${TEST_BINARY_DIR}"
        RESULT_VARIABLE compare_result
        OUTPUT_VARIABLE compare_stdout
        ERROR_VARIABLE compare_stderr
    )
    if(NOT compare_result EQUAL 0)
        message(FATAL_ERROR
            "${label} numerical comparison failed\n${compare_stdout}${compare_stderr}")
    endif()
endfunction()

# Cases 7-9: deterministic CNN/MLP execution, keys, shape, dtype, values.
compare_program(
    "cnn"
    "${cnn}"
    "${cnn_executor}"
    "inputs = {
    'Image': torch.arange(64, dtype=torch.float32).reshape(1, 1, 8, 8) / 64,
    'Filter': torch.full((2, 1, 3, 3), 0.125, dtype=torch.float32),
    'Classifier': torch.arange(72, dtype=torch.float32).reshape(18, 4) / 72,
}")
compare_program(
    "mlp"
    "${mlp}"
    "${mlp_executor}"
    "inputs = {
    'X': torch.arange(16, dtype=torch.float32).reshape(2, 8) / 16,
    'W1': torch.arange(128, dtype=torch.float32).reshape(8, 16) / 128,
    'B1': torch.full((2, 16), 0.25, dtype=torch.float32),
    'W2': torch.arange(64, dtype=torch.float32).reshape(16, 4) / 64,
    'B2': torch.full((2, 4), -0.5, dtype=torch.float32),
}")

# Cases 10 and 11: multiple outputs and Constant execution.
set(fixture_executor "${TEST_BINARY_DIR}/fixture-region.py")
compare_program(
    "fixture"
    "${fixture}"
    "${fixture_executor}"
    "inputs = {'X': torch.arange(4, dtype=torch.float32).reshape(2, 2)}")

# Case 12: overwrite.
file(WRITE "${cnn_executor}" "unrelated")
emit_executor("${cnn}" "${cnn_executor}" "overwrite")
file(READ "${cnn_executor}" overwritten)
string(FIND "${overwritten}" "unrelated" old_position)
if(NOT old_position EQUAL -1)
    message(FATAL_ERROR "overwrite retained old content")
endif()

# Case 13: missing output parent.
set(missing_parent "${TEST_BINARY_DIR}/missing-parent")
file(REMOVE_RECURSE "${missing_parent}")
set(missing_output "${missing_parent}/executor.py")
run_thiran(result stdout stderr
    --emit-region-executor "${cnn}" "${missing_output}")
require_equal("${result}" "4" "missing parent exit")
require_equal("${stdout}" "" "missing parent stdout")
require_equal(
    "${stderr}"
    "Failed to open Region executor output: ${missing_output}\n"
    "missing parent stderr")
if(EXISTS "${missing_parent}")
    message(FATAL_ERROR "missing parent was created")
endif()

# Case 14: source equals output.
set(source_copy "${TEST_BINARY_DIR}/source-copy.th")
file(COPY_FILE "${cnn}" "${source_copy}")
file(READ "${source_copy}" source_before)
run_thiran(result stdout stderr
    --emit-region-executor "${source_copy}" "${source_copy}")
require_equal("${result}" "4" "source protection exit")
require_equal("${stdout}" "" "source protection stdout")
require_equal(
    "${stderr}"
    "Refusing to overwrite source file with Region executor: ${source_copy}\n"
    "source protection stderr")
file(READ "${source_copy}" source_after)
require_equal("${source_after}" "${source_before}" "source preservation")

# Case 15: R5 plan modes.
run_thiran(result plan_stdout plan_stderr --plan "${cnn}")
require_equal("${result}" "0" "plan mode exit")
require_equal("${plan_stderr}" "" "plan mode stderr")
require_contains("${plan_stdout}" "HybridRegionPlan" "plan mode output")
set(plan_file "${TEST_BINARY_DIR}/plan.txt")
run_thiran(result emit_stdout emit_stderr
    --emit-plan "${cnn}" "${plan_file}")
require_equal("${result}" "0" "emit-plan exit")
require_equal("${emit_stderr}" "" "emit-plan stderr")

# Case 16: normal mode and generated Python remain executable.
foreach(source "${cnn}" "${mlp}")
    run_thiran(result stdout stderr "${source}")
    require_equal("${result}" "0" "normal mode exit")
    if(NOT EXISTS "${TEST_BINARY_DIR}/generated.py" OR
       NOT EXISTS "${TEST_BINARY_DIR}/graph.dot")
        message(FATAL_ERROR "normal mode artifacts absent")
    endif()
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env
            "CUDA_VISIBLE_DEVICES="
            "PYTHONDONTWRITEBYTECODE=1"
            "${PYTHON_EXECUTABLE}" "${TEST_BINARY_DIR}/generated.py"
        WORKING_DIRECTORY "${TEST_BINARY_DIR}"
        RESULT_VARIABLE python_result
        OUTPUT_VARIABLE python_stdout
        ERROR_VARIABLE python_stderr
    )
    if(NOT python_result EQUAL 0)
        message(FATAL_ERROR "normal generated Python failed\n${python_stderr}")
    endif()
endforeach()
